
services:
  postgresdb:
    container_name: pa-postgres
    image: ghcr.io/Martinhdeez/plane_assistant/db:latest
    restart: unless-stopped
    volumes: 
      - "postgres_data:/var/lib/postgresql"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "plane_assistant"
  backend:
    container_name: pa-fastapi
    image: ghcr.io/Martinhdeez/plane_assistant/api:latest
    restart: unless-stopped
    volumes:
      - "./config:/config"
      - "./uploads:/uploads"
    environment:
      WEB_CONCURRENCY: 4 # Number of workers (child processes)
    ports:
      - "8000:8000"
    depends_on:
      postgresdb:
        condition: service_healthy
  frontend:
    container_name: pa-website
    image: ghcr.io/Martinhdeez/plane_assistant/web:latest
    restart: unless-stopped
    environment:
      REAL_API_URL: 'http://localhost:8000' # Change to your API URL
    ports:
      - "8080:80"
    depends_on:
      postgresdb:
        condition: service_healthy
      backend:
        condition: service_healthy

volumes:
  postgres_data: